#' Example target population for weightflow
#'
#' A simulated population (sampling frame) of individuals nested in households,
#' with demographic auxiliaries and two outcomes. Used to illustrate calibration
#' targets and model calibration (`step_model_calibration`), and to validate
#' weighted estimates against the truth. Generated by `data-raw/weightflow_data.R`.
#'
#' @format A data frame with one row per person and the columns:
#' \describe{
#'   \item{person_id}{individual identifier}
#'   \item{household_id}{household identifier (cluster)}
#'   \item{region}{region: North, South, East or West}
#'   \item{sex}{F or M}
#'   \item{age}{age in years (18-95)}
#'   \item{income}{annual income}
#'   \item{employed}{employment indicator (0/1)}
#' }
"population"
#' Example survey sample for weightflow
#'
#' A stratified household sample drawn from `population`, with unequal design
#' base weights (inverse sampling fraction by region), an unknown-eligibility
#' flag and a response indicator. The frame auxiliaries (region, sex, age) are
#' known for every unit; the survey outcomes (income, employed) are observed
#' only for respondents. Generated by `data-raw/weightflow_data.R`.
#'
#' @format A data frame with one row per sampled person and the columns:
#' \describe{
#'   \item{person_id, household_id}{identifiers}
#'   \item{region, sex, age}{frame auxiliaries, known for all units}
#'   \item{pw}{design base weight (inverse sampling fraction)}
#'   \item{unknown_elig}{1 if eligibility is unknown}
#'   \item{responded}{1 if the unit responded}
#'   \item{income, employed}{survey outcomes; NA for nonrespondents}
#' }
"sample_survey"